title: OCP by Examples
description: 
theme: just-the-docs
color_scheme: dark

url: https://romdalf.github.io/ocp-projects
repository: romdalf/ocp-projects
permalinks: pretty

search_enabled: false
enable_copy_code_button: true

mermaid:
  version: "9.1.6"

aux_links:
  "OCP Projects": 
    - "https://github.com/romdalf/ocp-projects"

back_to_top: true
back_to_top_text: "Top"

footer_content: "MIT License"

