title: OCP by Examples
description: 
theme: just-the-docs
color_scheme: dark

url: https://romdalf.github.io/ocp-projects

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
